### ISSUE TITLE
formgator roadmap

### ISSUE THREAD

**Issue by GauBen** [GauBen/formgator#1]
formgator is currently developed alongside timeline to let me work on both at the same time, with a simple, portable workflow. When stable, formgator will be moved to its own repo.

Here's the roadmap to v1:

- [x] Claim the name on npm
- [x] Errors are useful and usable
- [x] All `<input type="...">` are supported
- [x] `""` is valid even with `minlength="1"`
- [x] Other form inputs are supported (`<select>`, `<textarea>`)
- [ ] Attributes are usable in HTML
- [ ] `.meta()` for form generation?
- [ ] formgator has its own repo
- [x] 100% code coverage
- [x] 100% type coverage (if that's a thing)
- [x] [SvelteKit] Decide between `(data, event) => {}` and `({ data, ...event }) => {}`
- [ ] Auto-publish with GitHub actions
- [x] Code structure scales (one validator per file)
- [ ] Integration with [Superforms](https://superforms.rocks/)
- [ ] v1!

**Comment by Eddie1O** [comment]
Hi @GauBen,

many thanks for this small yet awesome tool!

what do you think about extending functionality of this package to also cover `URLSearchParams`? I find them similarly annoying to work with as `FormData`. No pressure at all, I'd just like to hear your opinion about it.

**Comment by GauBen** [comment]
Hi @Eddie1O , good to see that you're still using formgator!

I have fantastic news for you: `URLSearchParams` are already supported, and if it doesn't work, it's a bug

Thank you for your constant support

**Comment by Eddie1O** [comment]
This arrived quicker than a pizza from down the street!
 I think I missed it from the docs.

Thanks a bunch!
